 language: node_js
 node_js: "lts/*"
 services:
     - mongodb
 deploy:
  provider: heroku
  api_key:
    secure: lJB40rBZ/j+BVmJEv7Krpl6+Bs7v6NiPTDvsv+X70rV0WfnIz0WZ5YgkA6cBmqCeZ1e85Fksp5m5nV8Ylg01eoOMZaWZwtALuScSFw8YGkI5m3XOlW2fOr+i/Abyt5ObB16Esjo0C4pywsOmxb4UKLU0ZDYCLOJnutkXmmBm1voVto+C+3H82s9Vco+lNdAGZQCdDcqJqNp8SIxRXYBBy+Rh3uEc/3OxqN4QmiywGeciNwluXwbn3f8PBua0NvYmUqLoBy7Usj5XIrg08J3O9hGNoy2JuNY9m9Hf5OnWXmGyM9Q8zeK+s135YNd2a2r+r3OTLCJr8Rr0oq4KxjbdR7CcKl9dNySUjGC+AyaRl5GiLzKne3usIR/F5A75oRj7GE3tf2JzsKsH/VlcyAzVTdPM3lOkbAt3TmRm042uEBL2dxEPrGV0y1mPNinvPY39L73y3ldAnRsPwufEZgYCQpBKU8hdZSUrMdyGXU7142lEQgUOFRg7YEk+1XFThRaPTJc0I1Aka4ELiWfW1wyNrmKnDzN+R7mJ2QMhvN+xp8+lJyql+GSlcoCb61xE29/4DVWBpVd92GrmT0PD5WqOzt80w3b+6AV3xkxZwfCTifZCByRqxhhgvVQcEL9IDzf4gtY6oCoykaFjsFmdYCylNJ6r5EBjh3tPA52HlCFEbuE=
  app: fierce-garden-79213
  on:
    repo: schamblee/blogtopic-api